### ISSUE TITLE
c stake command broken ? 

### ISSUE THREAD

**Issue by snafu69** [commune-ai/commune#90]
#### Describe the bug
go to stake to one of my validators and ends up erroring out

#### To Reproduce
c stake vali::storage.snafu0 300 key=module

####  Steps to reproduce the behavior
c stake vali::storage.snafu0 300 key=module
from a bash prompt on my machine

#### Expected behavior
Stake to be placed/

![image](https://github.com/commune-ai/commune/assets/29141379/220a425a-0c9d-4ad3-bbdb-14ad45406f44)
#### Specs
Ubuntu 22.04
Latest pull

**Comment by Supremesource** [comment]
@salvivona can you take a look at this please ?

**Comment by salvivona** [comment]
can you pull and try again. I believe this was fixed. lmk

**Comment by snafu69** [comment]
yea not fixed...

![image](https://github.com/commune-ai/commune/assets/29141379/0e96a1a6-fa30-48b6-ba37-9f9171b945dc)

**Comment by snafu69** [comment]
c key2stake still broken to and a few other commands
![image](https://github.com/commune-ai/commune/assets/29141379/91b37af3-22e3-4d79-b413-7ddc90d4769b)

**Comment by snafu69** [comment]
Cant even register a server atm according to c register I dont have enough to stake it on my root key but I have over 8600 as shown in screenshot
![image](https://github.com/commune-ai/commune/assets/29141379/5eb41a14-e7a8-4efb-8006-644933c53e75)

**Comment by salvivona** [comment]
This has been fixed. Please notify me if you have any issues
